version: '3.8'

services:
  fbmn-stats:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fbmn-stats-app
    ports:
      - "8502:8502"
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=512
    volumes:
      - ./assets:/app/assets:ro
      - ./example-data:/app/example-data:ro
      - ./pages:/app/pages:ro
      - ./src:/app/src:ro
      - ./.streamlit:/app/.streamlit:ro
      - app-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fbmn-stats.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.fbmn-stats.tls=true"
      - "traefik.http.routers.fbmn-stats.tls.certresolver=letsencrypt"
      - "traefik.http.services.fbmn-stats.loadbalancer.server.port=8502"

volumes:
  app-data:
    driver: local

networks:
  default:
    name: fbmn-stats-network
    driver: bridge