version: '3.8'

services:
  fbmn-stats:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_GLOBAL_DEVELOPMENT_MODE=false
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=512
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      - PYTHONPATH=/app
      # Coolify magic variables
      - SERVICE_FQDN_FBMN=${SERVICE_FQDN_FBMN}
    volumes:
      - app-data:/app/data
    expose:
      - "8502"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      # Coolify will automatically add required Traefik labels
      - "coolify.managed=true"

volumes:
  app-data:
    driver: local
